version: 2
jobs:
 build:
   machine: true
   filters: 
    branches:
     only:
      - develop
      - master
    
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t stkapp -f ./StockApp/Dockerfile .

     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag stkapp registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME
